//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 06:35:24 PM MEZ 
//


package at.ac.tuwien.ieg.asbruedit.model.asbru;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deltaLinkOrGmtLink",
    "bibrefOrCommentOrNotYetDefinedOrUrl",
    "dimensionDef",
    "arrayDefOrListDefOrMultiSetDefOrRecordDefOrScalarDefOrSetDef"
})
@XmlRootElement(name = "array-def")
public class ArrayDef {

    @XmlElements({
        @XmlElement(name = "delta-link", type = DeltaLink.class),
        @XmlElement(name = "gmt-link", type = GmtLink.class)
    })
    protected List<Object> deltaLinkOrGmtLink;
    @XmlElements({
        @XmlElement(name = "bibref", type = Bibref.class),
        @XmlElement(name = "comment", type = Comment.class),
        @XmlElement(name = "not-yet-defined", type = NotYetDefined.class),
        @XmlElement(name = "url", type = Url.class)
    })
    protected List<Object> bibrefOrCommentOrNotYetDefinedOrUrl;
    @XmlElement(name = "dimension-def", required = true)
    protected List<DimensionDef> dimensionDef;
    @XmlElements({
        @XmlElement(name = "array-def", required = true, type = ArrayDef.class),
        @XmlElement(name = "list-def", required = true, type = ListDef.class),
        @XmlElement(name = "multi-set-def", required = true, type = MultiSetDef.class),
        @XmlElement(name = "record-def", required = true, type = RecordDef.class),
        @XmlElement(name = "scalar-def", required = true, type = ScalarDef.class),
        @XmlElement(name = "set-def", required = true, type = SetDef.class)
    })
    protected List<Object> arrayDefOrListDefOrMultiSetDefOrRecordDefOrScalarDefOrSetDef;

    /**
     * Gets the value of the deltaLinkOrGmtLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deltaLinkOrGmtLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeltaLinkOrGmtLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeltaLink }
     * {@link GmtLink }
     * 
     * 
     */
    public List<Object> getDeltaLinkOrGmtLink() {
        if (deltaLinkOrGmtLink == null) {
            deltaLinkOrGmtLink = new ArrayList<Object>();
        }
        return this.deltaLinkOrGmtLink;
    }

    /**
     * Gets the value of the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBibrefOrCommentOrNotYetDefinedOrUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bibref }
     * {@link Comment }
     * {@link NotYetDefined }
     * {@link Url }
     * 
     * 
     */
    public List<Object> getBibrefOrCommentOrNotYetDefinedOrUrl() {
        if (bibrefOrCommentOrNotYetDefinedOrUrl == null) {
            bibrefOrCommentOrNotYetDefinedOrUrl = new ArrayList<Object>();
        }
        return this.bibrefOrCommentOrNotYetDefinedOrUrl;
    }

    /**
     * Gets the value of the dimensionDef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dimensionDef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDimensionDef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DimensionDef }
     * 
     * 
     */
    public List<DimensionDef> getDimensionDef() {
        if (dimensionDef == null) {
            dimensionDef = new ArrayList<DimensionDef>();
        }
        return this.dimensionDef;
    }

    /**
     * Gets the value of the arrayDefOrListDefOrMultiSetDefOrRecordDefOrScalarDefOrSetDef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arrayDefOrListDefOrMultiSetDefOrRecordDefOrScalarDefOrSetDef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArrayDefOrListDefOrMultiSetDefOrRecordDefOrScalarDefOrSetDef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArrayDef }
     * {@link ListDef }
     * {@link MultiSetDef }
     * {@link RecordDef }
     * {@link ScalarDef }
     * {@link SetDef }
     * 
     * 
     */
    public List<Object> getArrayDefOrListDefOrMultiSetDefOrRecordDefOrScalarDefOrSetDef() {
        if (arrayDefOrListDefOrMultiSetDefOrRecordDefOrScalarDefOrSetDef == null) {
            arrayDefOrListDefOrMultiSetDefOrRecordDefOrScalarDefOrSetDef = new ArrayList<Object>();
        }
        return this.arrayDefOrListDefOrMultiSetDefOrRecordDefOrScalarDefOrSetDef;
    }

}
