//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 06:35:24 PM MEZ 
//


package at.ac.tuwien.ieg.asbruedit.model.asbru;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deltaLinkOrGmtLink",
    "bibrefOrCommentOrNotYetDefinedOrUrl",
    "argumentRefOrArrayRefOrConstantRefOrFieldRefOrFunctionCallOrGetPositionOrListRefOrMultiSetRefOrNowOrNumericalConstantOrOperationOrParameterRefOrPlanStateTransitionOrQualitativeConstantOrSelfOrSetRefOrStringConstantOrVariableRef"
})
@XmlRootElement(name = "explanation")
public class Explanation {

    @XmlAttribute(name = "text")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String text;
    @XmlElements({
        @XmlElement(name = "delta-link", type = DeltaLink.class),
        @XmlElement(name = "gmt-link", type = GmtLink.class)
    })
    protected List<Object> deltaLinkOrGmtLink;
    @XmlElements({
        @XmlElement(name = "bibref", type = Bibref.class),
        @XmlElement(name = "comment", type = Comment.class),
        @XmlElement(name = "not-yet-defined", type = NotYetDefined.class),
        @XmlElement(name = "url", type = Url.class)
    })
    protected List<Object> bibrefOrCommentOrNotYetDefinedOrUrl;
    @XmlElements({
        @XmlElement(name = "argument-ref", type = ArgumentRef.class),
        @XmlElement(name = "array-ref", type = ArrayRef.class),
        @XmlElement(name = "constant-ref", type = ConstantRef.class),
        @XmlElement(name = "field-ref", type = FieldRef.class),
        @XmlElement(name = "function-call", type = FunctionCall.class),
        @XmlElement(name = "get-position", type = GetPosition.class),
        @XmlElement(name = "list-ref", type = ListRef.class),
        @XmlElement(name = "multi-set-ref", type = MultiSetRef.class),
        @XmlElement(name = "now", type = Now.class),
        @XmlElement(name = "numerical-constant", type = NumericalConstant.class),
        @XmlElement(name = "operation", type = Operation.class),
        @XmlElement(name = "parameter-ref", type = ParameterRef.class),
        @XmlElement(name = "plan-state-transition", type = PlanStateTransition.class),
        @XmlElement(name = "qualitative-constant", type = QualitativeConstant.class),
        @XmlElement(name = "self", type = Self.class),
        @XmlElement(name = "set-ref", type = SetRef.class),
        @XmlElement(name = "string-constant", type = StringConstant.class),
        @XmlElement(name = "variable-ref", type = VariableRef.class)
    })
    protected List<Object> argumentRefOrArrayRefOrConstantRefOrFieldRefOrFunctionCallOrGetPositionOrListRefOrMultiSetRefOrNowOrNumericalConstantOrOperationOrParameterRefOrPlanStateTransitionOrQualitativeConstantOrSelfOrSetRefOrStringConstantOrVariableRef;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the deltaLinkOrGmtLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deltaLinkOrGmtLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeltaLinkOrGmtLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeltaLink }
     * {@link GmtLink }
     * 
     * 
     */
    public List<Object> getDeltaLinkOrGmtLink() {
        if (deltaLinkOrGmtLink == null) {
            deltaLinkOrGmtLink = new ArrayList<Object>();
        }
        return this.deltaLinkOrGmtLink;
    }

    /**
     * Gets the value of the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBibrefOrCommentOrNotYetDefinedOrUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bibref }
     * {@link Comment }
     * {@link NotYetDefined }
     * {@link Url }
     * 
     * 
     */
    public List<Object> getBibrefOrCommentOrNotYetDefinedOrUrl() {
        if (bibrefOrCommentOrNotYetDefinedOrUrl == null) {
            bibrefOrCommentOrNotYetDefinedOrUrl = new ArrayList<Object>();
        }
        return this.bibrefOrCommentOrNotYetDefinedOrUrl;
    }

    /**
     * Gets the value of the argumentRefOrArrayRefOrConstantRefOrFieldRefOrFunctionCallOrGetPositionOrListRefOrMultiSetRefOrNowOrNumericalConstantOrOperationOrParameterRefOrPlanStateTransitionOrQualitativeConstantOrSelfOrSetRefOrStringConstantOrVariableRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the argumentRefOrArrayRefOrConstantRefOrFieldRefOrFunctionCallOrGetPositionOrListRefOrMultiSetRefOrNowOrNumericalConstantOrOperationOrParameterRefOrPlanStateTransitionOrQualitativeConstantOrSelfOrSetRefOrStringConstantOrVariableRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArgumentRefOrArrayRefOrConstantRefOrFieldRefOrFunctionCallOrGetPositionOrListRefOrMultiSetRefOrNowOrNumericalConstantOrOperationOrParameterRefOrPlanStateTransitionOrQualitativeConstantOrSelfOrSetRefOrStringConstantOrVariableRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArgumentRef }
     * {@link ArrayRef }
     * {@link ConstantRef }
     * {@link FieldRef }
     * {@link FunctionCall }
     * {@link GetPosition }
     * {@link ListRef }
     * {@link MultiSetRef }
     * {@link Now }
     * {@link NumericalConstant }
     * {@link Operation }
     * {@link ParameterRef }
     * {@link PlanStateTransition }
     * {@link QualitativeConstant }
     * {@link Self }
     * {@link SetRef }
     * {@link StringConstant }
     * {@link VariableRef }
     * 
     * 
     */
    public List<Object> getArgumentRefOrArrayRefOrConstantRefOrFieldRefOrFunctionCallOrGetPositionOrListRefOrMultiSetRefOrNowOrNumericalConstantOrOperationOrParameterRefOrPlanStateTransitionOrQualitativeConstantOrSelfOrSetRefOrStringConstantOrVariableRef() {
        if (argumentRefOrArrayRefOrConstantRefOrFieldRefOrFunctionCallOrGetPositionOrListRefOrMultiSetRefOrNowOrNumericalConstantOrOperationOrParameterRefOrPlanStateTransitionOrQualitativeConstantOrSelfOrSetRefOrStringConstantOrVariableRef == null) {
            argumentRefOrArrayRefOrConstantRefOrFieldRefOrFunctionCallOrGetPositionOrListRefOrMultiSetRefOrNowOrNumericalConstantOrOperationOrParameterRefOrPlanStateTransitionOrQualitativeConstantOrSelfOrSetRefOrStringConstantOrVariableRef = new ArrayList<Object>();
        }
        return this.argumentRefOrArrayRefOrConstantRefOrFieldRefOrFunctionCallOrGetPositionOrListRefOrMultiSetRefOrNowOrNumericalConstantOrOperationOrParameterRefOrPlanStateTransitionOrQualitativeConstantOrSelfOrSetRefOrStringConstantOrVariableRef;
    }

}
