//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 06:35:24 PM MEZ 
//


package at.ac.tuwien.ieg.asbruedit.model.asbru;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deltaLinkOrGmtLink",
    "bibrefOrCommentOrNotYetDefinedOrUrl",
    "explanation",
    "doBefore",
    "doForEach",
    "terminationCondition",
    "doAfter"
})
@XmlRootElement(name = "for-each-plan")
public class ForEachPlan {

    @XmlAttribute(name = "subplan-ordering", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String subplanOrdering;
    @XmlAttribute(name = "wait-for-children")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String waitForChildren;
    @XmlAttribute(name = "propagation-specification")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String propagationSpecification;
    @XmlElements({
        @XmlElement(name = "delta-link", type = DeltaLink.class),
        @XmlElement(name = "gmt-link", type = GmtLink.class)
    })
    protected List<Object> deltaLinkOrGmtLink;
    @XmlElements({
        @XmlElement(name = "bibref", type = Bibref.class),
        @XmlElement(name = "comment", type = Comment.class),
        @XmlElement(name = "not-yet-defined", type = NotYetDefined.class),
        @XmlElement(name = "url", type = Url.class)
    })
    protected List<Object> bibrefOrCommentOrNotYetDefinedOrUrl;
    protected List<Explanation> explanation;
    @XmlElement(name = "do-before")
    protected DoBefore doBefore;
    @XmlElement(name = "do-for-each", required = true)
    protected DoForEach doForEach;
    @XmlElement(name = "termination-condition", required = true)
    protected TerminationCondition terminationCondition;
    @XmlElement(name = "do-after")
    protected DoAfter doAfter;

    /**
     * Gets the value of the subplanOrdering property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubplanOrdering() {
        return subplanOrdering;
    }

    /**
     * Sets the value of the subplanOrdering property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubplanOrdering(String value) {
        this.subplanOrdering = value;
    }

    /**
     * Gets the value of the waitForChildren property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaitForChildren() {
        if (waitForChildren == null) {
            return "yes";
        } else {
            return waitForChildren;
        }
    }

    /**
     * Sets the value of the waitForChildren property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaitForChildren(String value) {
        this.waitForChildren = value;
    }

    /**
     * Gets the value of the propagationSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropagationSpecification() {
        if (propagationSpecification == null) {
            return "aborted-or-rejected";
        } else {
            return propagationSpecification;
        }
    }

    /**
     * Sets the value of the propagationSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropagationSpecification(String value) {
        this.propagationSpecification = value;
    }

    /**
     * Gets the value of the deltaLinkOrGmtLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deltaLinkOrGmtLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeltaLinkOrGmtLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeltaLink }
     * {@link GmtLink }
     * 
     * 
     */
    public List<Object> getDeltaLinkOrGmtLink() {
        if (deltaLinkOrGmtLink == null) {
            deltaLinkOrGmtLink = new ArrayList<Object>();
        }
        return this.deltaLinkOrGmtLink;
    }

    /**
     * Gets the value of the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBibrefOrCommentOrNotYetDefinedOrUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bibref }
     * {@link Comment }
     * {@link NotYetDefined }
     * {@link Url }
     * 
     * 
     */
    public List<Object> getBibrefOrCommentOrNotYetDefinedOrUrl() {
        if (bibrefOrCommentOrNotYetDefinedOrUrl == null) {
            bibrefOrCommentOrNotYetDefinedOrUrl = new ArrayList<Object>();
        }
        return this.bibrefOrCommentOrNotYetDefinedOrUrl;
    }

    /**
     * Gets the value of the explanation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the explanation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExplanation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Explanation }
     * 
     * 
     */
    public List<Explanation> getExplanation() {
        if (explanation == null) {
            explanation = new ArrayList<Explanation>();
        }
        return this.explanation;
    }

    /**
     * Gets the value of the doBefore property.
     * 
     * @return
     *     possible object is
     *     {@link DoBefore }
     *     
     */
    public DoBefore getDoBefore() {
        return doBefore;
    }

    /**
     * Sets the value of the doBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoBefore }
     *     
     */
    public void setDoBefore(DoBefore value) {
        this.doBefore = value;
    }

    /**
     * Gets the value of the doForEach property.
     * 
     * @return
     *     possible object is
     *     {@link DoForEach }
     *     
     */
    public DoForEach getDoForEach() {
        return doForEach;
    }

    /**
     * Sets the value of the doForEach property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoForEach }
     *     
     */
    public void setDoForEach(DoForEach value) {
        this.doForEach = value;
    }

    /**
     * Gets the value of the terminationCondition property.
     * 
     * @return
     *     possible object is
     *     {@link TerminationCondition }
     *     
     */
    public TerminationCondition getTerminationCondition() {
        return terminationCondition;
    }

    /**
     * Sets the value of the terminationCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminationCondition }
     *     
     */
    public void setTerminationCondition(TerminationCondition value) {
        this.terminationCondition = value;
    }

    /**
     * Gets the value of the doAfter property.
     * 
     * @return
     *     possible object is
     *     {@link DoAfter }
     *     
     */
    public DoAfter getDoAfter() {
        return doAfter;
    }

    /**
     * Sets the value of the doAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoAfter }
     *     
     */
    public void setDoAfter(DoAfter value) {
        this.doAfter = value;
    }

}
