//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 06:35:24 PM MEZ 
//


package at.ac.tuwien.ieg.asbruedit.model.asbru;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deltaLinkOrGmtLink",
    "bibrefOrCommentOrNotYetDefinedOrUrl",
    "explanation",
    "isKnownParameterOrIsUnknownParameterOrValueDescriptionOrValueRange",
    "context",
    "timeAnnotation",
    "samplingFrequency"
})
@XmlRootElement(name = "parameter-proposition")
public class ParameterProposition {

    @XmlAttribute(name = "parameter-name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String parameterName;
    @XmlAttribute(name = "label")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String label;
    @XmlAttribute(name = "importance")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String importance;
    @XmlElements({
        @XmlElement(name = "delta-link", type = DeltaLink.class),
        @XmlElement(name = "gmt-link", type = GmtLink.class)
    })
    protected List<Object> deltaLinkOrGmtLink;
    @XmlElements({
        @XmlElement(name = "bibref", type = Bibref.class),
        @XmlElement(name = "comment", type = Comment.class),
        @XmlElement(name = "not-yet-defined", type = NotYetDefined.class),
        @XmlElement(name = "url", type = Url.class)
    })
    protected List<Object> bibrefOrCommentOrNotYetDefinedOrUrl;
    protected List<Explanation> explanation;
    @XmlElements({
        @XmlElement(name = "is-known-parameter", required = true, type = IsKnownParameter.class),
        @XmlElement(name = "is-unknown-parameter", required = true, type = IsUnknownParameter.class),
        @XmlElement(name = "value-description", required = true, type = ValueDescription.class),
        @XmlElement(name = "value-range", required = true, type = ValueRange.class)
    })
    protected List<Object> isKnownParameterOrIsUnknownParameterOrValueDescriptionOrValueRange;
    @XmlElement(required = true)
    protected Context context;
    @XmlElement(name = "time-annotation", required = true)
    protected TimeAnnotation timeAnnotation;
    @XmlElement(name = "sampling-frequency")
    protected SamplingFrequency samplingFrequency;

    /**
     * Gets the value of the parameterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterName() {
        return parameterName;
    }

    /**
     * Sets the value of the parameterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterName(String value) {
        this.parameterName = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the importance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportance() {
        return importance;
    }

    /**
     * Sets the value of the importance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportance(String value) {
        this.importance = value;
    }

    /**
     * Gets the value of the deltaLinkOrGmtLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deltaLinkOrGmtLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeltaLinkOrGmtLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeltaLink }
     * {@link GmtLink }
     * 
     * 
     */
    public List<Object> getDeltaLinkOrGmtLink() {
        if (deltaLinkOrGmtLink == null) {
            deltaLinkOrGmtLink = new ArrayList<Object>();
        }
        return this.deltaLinkOrGmtLink;
    }

    /**
     * Gets the value of the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBibrefOrCommentOrNotYetDefinedOrUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bibref }
     * {@link Comment }
     * {@link NotYetDefined }
     * {@link Url }
     * 
     * 
     */
    public List<Object> getBibrefOrCommentOrNotYetDefinedOrUrl() {
        if (bibrefOrCommentOrNotYetDefinedOrUrl == null) {
            bibrefOrCommentOrNotYetDefinedOrUrl = new ArrayList<Object>();
        }
        return this.bibrefOrCommentOrNotYetDefinedOrUrl;
    }

    /**
     * Gets the value of the explanation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the explanation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExplanation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Explanation }
     * 
     * 
     */
    public List<Explanation> getExplanation() {
        if (explanation == null) {
            explanation = new ArrayList<Explanation>();
        }
        return this.explanation;
    }

    /**
     * Gets the value of the isKnownParameterOrIsUnknownParameterOrValueDescriptionOrValueRange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isKnownParameterOrIsUnknownParameterOrValueDescriptionOrValueRange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsKnownParameterOrIsUnknownParameterOrValueDescriptionOrValueRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IsKnownParameter }
     * {@link IsUnknownParameter }
     * {@link ValueDescription }
     * {@link ValueRange }
     * 
     * 
     */
    public List<Object> getIsKnownParameterOrIsUnknownParameterOrValueDescriptionOrValueRange() {
        if (isKnownParameterOrIsUnknownParameterOrValueDescriptionOrValueRange == null) {
            isKnownParameterOrIsUnknownParameterOrValueDescriptionOrValueRange = new ArrayList<Object>();
        }
        return this.isKnownParameterOrIsUnknownParameterOrValueDescriptionOrValueRange;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link Context }
     *     
     */
    public Context getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link Context }
     *     
     */
    public void setContext(Context value) {
        this.context = value;
    }

    /**
     * Gets the value of the timeAnnotation property.
     * 
     * @return
     *     possible object is
     *     {@link TimeAnnotation }
     *     
     */
    public TimeAnnotation getTimeAnnotation() {
        return timeAnnotation;
    }

    /**
     * Sets the value of the timeAnnotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeAnnotation }
     *     
     */
    public void setTimeAnnotation(TimeAnnotation value) {
        this.timeAnnotation = value;
    }

    /**
     * Gets the value of the samplingFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link SamplingFrequency }
     *     
     */
    public SamplingFrequency getSamplingFrequency() {
        return samplingFrequency;
    }

    /**
     * Sets the value of the samplingFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamplingFrequency }
     *     
     */
    public void setSamplingFrequency(SamplingFrequency value) {
        this.samplingFrequency = value;
    }

}
