//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 06:35:24 PM MEZ 
//


package at.ac.tuwien.ieg.asbruedit.model.asbru;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deltaLinkOrGmtLink",
    "bibrefOrCommentOrNotYetDefinedOrUrl",
    "libraryInfo",
    "domainDefs",
    "libraryDefs",
    "plans"
})
@XmlRootElement(name = "plan-library")
public class PlanLibrary {

    @XmlElements({
        @XmlElement(name = "delta-link", type = DeltaLink.class),
        @XmlElement(name = "gmt-link", type = GmtLink.class)
    })
    protected List<Object> deltaLinkOrGmtLink;
    @XmlElements({
        @XmlElement(name = "bibref", type = Bibref.class),
        @XmlElement(name = "comment", type = Comment.class),
        @XmlElement(name = "not-yet-defined", type = NotYetDefined.class),
        @XmlElement(name = "url", type = Url.class)
    })
    protected List<Object> bibrefOrCommentOrNotYetDefinedOrUrl;
    @XmlElement(name = "library-info")
    protected LibraryInfo libraryInfo;
    @XmlElement(name = "domain-defs")
    protected DomainDefs domainDefs;
    @XmlElement(name = "library-defs")
    protected LibraryDefs libraryDefs;
    @XmlElement(required = true)
    protected Plans plans;

    /**
     * Gets the value of the deltaLinkOrGmtLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deltaLinkOrGmtLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeltaLinkOrGmtLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeltaLink }
     * {@link GmtLink }
     * 
     * 
     */
    public List<Object> getDeltaLinkOrGmtLink() {
        if (deltaLinkOrGmtLink == null) {
            deltaLinkOrGmtLink = new ArrayList<Object>();
        }
        return this.deltaLinkOrGmtLink;
    }

    /**
     * Gets the value of the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBibrefOrCommentOrNotYetDefinedOrUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bibref }
     * {@link Comment }
     * {@link NotYetDefined }
     * {@link Url }
     * 
     * 
     */
    public List<Object> getBibrefOrCommentOrNotYetDefinedOrUrl() {
        if (bibrefOrCommentOrNotYetDefinedOrUrl == null) {
            bibrefOrCommentOrNotYetDefinedOrUrl = new ArrayList<Object>();
        }
        return this.bibrefOrCommentOrNotYetDefinedOrUrl;
    }

    /**
     * Gets the value of the libraryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LibraryInfo }
     *     
     */
    public LibraryInfo getLibraryInfo() {
        return libraryInfo;
    }

    /**
     * Sets the value of the libraryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LibraryInfo }
     *     
     */
    public void setLibraryInfo(LibraryInfo value) {
        this.libraryInfo = value;
    }

    /**
     * Gets the value of the domainDefs property.
     * 
     * @return
     *     possible object is
     *     {@link DomainDefs }
     *     
     */
    public DomainDefs getDomainDefs() {
        return domainDefs;
    }

    /**
     * Sets the value of the domainDefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainDefs }
     *     
     */
    public void setDomainDefs(DomainDefs value) {
        this.domainDefs = value;
    }

    /**
     * Gets the value of the libraryDefs property.
     * 
     * @return
     *     possible object is
     *     {@link LibraryDefs }
     *     
     */
    public LibraryDefs getLibraryDefs() {
        return libraryDefs;
    }

    /**
     * Sets the value of the libraryDefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link LibraryDefs }
     *     
     */
    public void setLibraryDefs(LibraryDefs value) {
        this.libraryDefs = value;
    }

    /**
     * Gets the value of the plans property.
     * 
     * @return
     *     possible object is
     *     {@link Plans }
     *     
     */
    public Plans getPlans() {
        return plans;
    }

    /**
     * Sets the value of the plans property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plans }
     *     
     */
    public void setPlans(Plans value) {
        this.plans = value;
    }

}
