//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 06:35:24 PM MEZ 
//


package at.ac.tuwien.ieg.asbruedit.model.asbru;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deltaLinkOrGmtLink",
    "bibrefOrCommentOrNotYetDefinedOrUrl",
    "timeWindowSize",
    "stepWidth",
    "minimumOfValidPoints",
    "sourceOrUpperLimitOrLowerLimit"
})
@XmlRootElement(name = "spread-def")
public class SpreadDef {

    @XmlElements({
        @XmlElement(name = "delta-link", type = DeltaLink.class),
        @XmlElement(name = "gmt-link", type = GmtLink.class)
    })
    protected List<Object> deltaLinkOrGmtLink;
    @XmlElements({
        @XmlElement(name = "bibref", type = Bibref.class),
        @XmlElement(name = "comment", type = Comment.class),
        @XmlElement(name = "not-yet-defined", type = NotYetDefined.class),
        @XmlElement(name = "url", type = Url.class)
    })
    protected List<Object> bibrefOrCommentOrNotYetDefinedOrUrl;
    @XmlElement(name = "time-window-size")
    protected TimeWindowSize timeWindowSize;
    @XmlElement(name = "step-width")
    protected StepWidth stepWidth;
    @XmlElement(name = "minimum-of-valid-points")
    protected MinimumOfValidPoints minimumOfValidPoints;
    @XmlElements({
        @XmlElement(name = "source", required = true, type = Source.class),
        @XmlElement(name = "upper-limit", required = true, type = UpperLimit.class),
        @XmlElement(name = "lower-limit", required = true, type = LowerLimit.class)
    })
    protected List<Object> sourceOrUpperLimitOrLowerLimit;

    /**
     * Gets the value of the deltaLinkOrGmtLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deltaLinkOrGmtLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeltaLinkOrGmtLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeltaLink }
     * {@link GmtLink }
     * 
     * 
     */
    public List<Object> getDeltaLinkOrGmtLink() {
        if (deltaLinkOrGmtLink == null) {
            deltaLinkOrGmtLink = new ArrayList<Object>();
        }
        return this.deltaLinkOrGmtLink;
    }

    /**
     * Gets the value of the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bibrefOrCommentOrNotYetDefinedOrUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBibrefOrCommentOrNotYetDefinedOrUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bibref }
     * {@link Comment }
     * {@link NotYetDefined }
     * {@link Url }
     * 
     * 
     */
    public List<Object> getBibrefOrCommentOrNotYetDefinedOrUrl() {
        if (bibrefOrCommentOrNotYetDefinedOrUrl == null) {
            bibrefOrCommentOrNotYetDefinedOrUrl = new ArrayList<Object>();
        }
        return this.bibrefOrCommentOrNotYetDefinedOrUrl;
    }

    /**
     * Gets the value of the timeWindowSize property.
     * 
     * @return
     *     possible object is
     *     {@link TimeWindowSize }
     *     
     */
    public TimeWindowSize getTimeWindowSize() {
        return timeWindowSize;
    }

    /**
     * Sets the value of the timeWindowSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeWindowSize }
     *     
     */
    public void setTimeWindowSize(TimeWindowSize value) {
        this.timeWindowSize = value;
    }

    /**
     * Gets the value of the stepWidth property.
     * 
     * @return
     *     possible object is
     *     {@link StepWidth }
     *     
     */
    public StepWidth getStepWidth() {
        return stepWidth;
    }

    /**
     * Sets the value of the stepWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepWidth }
     *     
     */
    public void setStepWidth(StepWidth value) {
        this.stepWidth = value;
    }

    /**
     * Gets the value of the minimumOfValidPoints property.
     * 
     * @return
     *     possible object is
     *     {@link MinimumOfValidPoints }
     *     
     */
    public MinimumOfValidPoints getMinimumOfValidPoints() {
        return minimumOfValidPoints;
    }

    /**
     * Sets the value of the minimumOfValidPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinimumOfValidPoints }
     *     
     */
    public void setMinimumOfValidPoints(MinimumOfValidPoints value) {
        this.minimumOfValidPoints = value;
    }

    /**
     * Gets the value of the sourceOrUpperLimitOrLowerLimit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceOrUpperLimitOrLowerLimit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceOrUpperLimitOrLowerLimit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Source }
     * {@link UpperLimit }
     * {@link LowerLimit }
     * 
     * 
     */
    public List<Object> getSourceOrUpperLimitOrLowerLimit() {
        if (sourceOrUpperLimitOrLowerLimit == null) {
            sourceOrUpperLimitOrLowerLimit = new ArrayList<Object>();
        }
        return this.sourceOrUpperLimitOrLowerLimit;
    }

}
