//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 06:35:24 PM MEZ 
//


package at.ac.tuwien.ieg.asbruedit.model.asbru;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deltaLinkOrGmtLinkOrBibrefOrCommentOrNotYetDefinedOrUrlOrExplanationOrConstraintCombinationOrConstraintNotOrCountConstraintOrIsAutomaticOrIsManualOrNoneOrParameterPropositionOrParameterRefOrPlanStateConstraintOrReferToOrSimpleConditionOrTemporalConstraintOrToBeDefined"
})
@XmlRootElement(name = "temporal-constraint")
public class TemporalConstraint {

    @XmlAttribute(name = "label")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String label;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "importance")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String importance;
    @XmlElements({
        @XmlElement(name = "delta-link", type = DeltaLink.class),
        @XmlElement(name = "gmt-link", type = GmtLink.class),
        @XmlElement(name = "bibref", type = Bibref.class),
        @XmlElement(name = "comment", type = Comment.class),
        @XmlElement(name = "not-yet-defined", type = NotYetDefined.class),
        @XmlElement(name = "url", type = Url.class),
        @XmlElement(name = "explanation", type = Explanation.class),
        @XmlElement(name = "constraint-combination", type = ConstraintCombination.class),
        @XmlElement(name = "constraint-not", type = ConstraintNot.class),
        @XmlElement(name = "count-constraint", type = CountConstraint.class),
        @XmlElement(name = "is-automatic", type = IsAutomatic.class),
        @XmlElement(name = "is-manual", type = IsManual.class),
        @XmlElement(name = "none", type = None.class),
        @XmlElement(name = "parameter-proposition", type = ParameterProposition.class),
        @XmlElement(name = "parameter-ref", type = ParameterRef.class),
        @XmlElement(name = "plan-state-constraint", type = PlanStateConstraint.class),
        @XmlElement(name = "refer-to", type = ReferTo.class),
        @XmlElement(name = "simple-condition", type = SimpleCondition.class),
        @XmlElement(name = "temporal-constraint", type = TemporalConstraint.class),
        @XmlElement(name = "to-be-defined", type = ToBeDefined.class)
    })
    protected List<Object> deltaLinkOrGmtLinkOrBibrefOrCommentOrNotYetDefinedOrUrlOrExplanationOrConstraintCombinationOrConstraintNotOrCountConstraintOrIsAutomaticOrIsManualOrNoneOrParameterPropositionOrParameterRefOrPlanStateConstraintOrReferToOrSimpleConditionOrTemporalConstraintOrToBeDefined;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the importance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportance() {
        return importance;
    }

    /**
     * Sets the value of the importance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportance(String value) {
        this.importance = value;
    }

    /**
     * Gets the value of the deltaLinkOrGmtLinkOrBibrefOrCommentOrNotYetDefinedOrUrlOrExplanationOrConstraintCombinationOrConstraintNotOrCountConstraintOrIsAutomaticOrIsManualOrNoneOrParameterPropositionOrParameterRefOrPlanStateConstraintOrReferToOrSimpleConditionOrTemporalConstraintOrToBeDefined property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deltaLinkOrGmtLinkOrBibrefOrCommentOrNotYetDefinedOrUrlOrExplanationOrConstraintCombinationOrConstraintNotOrCountConstraintOrIsAutomaticOrIsManualOrNoneOrParameterPropositionOrParameterRefOrPlanStateConstraintOrReferToOrSimpleConditionOrTemporalConstraintOrToBeDefined property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeltaLinkOrGmtLinkOrBibrefOrCommentOrNotYetDefinedOrUrlOrExplanationOrConstraintCombinationOrConstraintNotOrCountConstraintOrIsAutomaticOrIsManualOrNoneOrParameterPropositionOrParameterRefOrPlanStateConstraintOrReferToOrSimpleConditionOrTemporalConstraintOrToBeDefined().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeltaLink }
     * {@link GmtLink }
     * {@link Bibref }
     * {@link Comment }
     * {@link NotYetDefined }
     * {@link Url }
     * {@link Explanation }
     * {@link ConstraintCombination }
     * {@link ConstraintNot }
     * {@link CountConstraint }
     * {@link IsAutomatic }
     * {@link IsManual }
     * {@link None }
     * {@link ParameterProposition }
     * {@link ParameterRef }
     * {@link PlanStateConstraint }
     * {@link ReferTo }
     * {@link SimpleCondition }
     * {@link TemporalConstraint }
     * {@link ToBeDefined }
     * 
     * 
     */
    public List<Object> getDeltaLinkOrGmtLinkOrBibrefOrCommentOrNotYetDefinedOrUrlOrExplanationOrConstraintCombinationOrConstraintNotOrCountConstraintOrIsAutomaticOrIsManualOrNoneOrParameterPropositionOrParameterRefOrPlanStateConstraintOrReferToOrSimpleConditionOrTemporalConstraintOrToBeDefined() {
        if (deltaLinkOrGmtLinkOrBibrefOrCommentOrNotYetDefinedOrUrlOrExplanationOrConstraintCombinationOrConstraintNotOrCountConstraintOrIsAutomaticOrIsManualOrNoneOrParameterPropositionOrParameterRefOrPlanStateConstraintOrReferToOrSimpleConditionOrTemporalConstraintOrToBeDefined == null) {
            deltaLinkOrGmtLinkOrBibrefOrCommentOrNotYetDefinedOrUrlOrExplanationOrConstraintCombinationOrConstraintNotOrCountConstraintOrIsAutomaticOrIsManualOrNoneOrParameterPropositionOrParameterRefOrPlanStateConstraintOrReferToOrSimpleConditionOrTemporalConstraintOrToBeDefined = new ArrayList<Object>();
        }
        return this.deltaLinkOrGmtLinkOrBibrefOrCommentOrNotYetDefinedOrUrlOrExplanationOrConstraintCombinationOrConstraintNotOrCountConstraintOrIsAutomaticOrIsManualOrNoneOrParameterPropositionOrParameterRefOrPlanStateConstraintOrReferToOrSimpleConditionOrTemporalConstraintOrToBeDefined;
    }

}
