package at.ac.tuwien.ieg.asbruedit.editor;

public interface AsbruModelFieldNames {
	public static final String PLAN_BODY_CHILDREN = "askOrCyclicalPlanOrForEachPlanOrGoToNextOrGoToPreviousOrIfThenElseOrInsertAfterIteratorOrInsertAfterPositionOrInsertBeforeIteratorOrInsertBeforePositionOrIterativePlanOrParameterAssignmentOrPlanActivationOrPutFirstOrPutLastOrReferToOrRemoveAtIteratorOrRemoveAtPositionOrRemoveElementOrResetIteratorOrSetContextOrSetIteratorOrSubplansOrToBeDefinedOrUserPerformedOrVariableAssignment";
	public static final String CYCLICAL_PLAN_BODY_CHILDREN = "askOrCyclicalPlanOrForEachPlanOrGoToNextOrGoToPreviousOrIfThenElseOrInsertAfterIteratorOrInsertAfterPositionOrInsertBeforeIteratorOrInsertBeforePositionOrIterativePlanOrParameterAssignmentOrPlanActivationOrPutFirstOrPutLastOrReferToOrRemoveAtIteratorOrRemoveAtPositionOrRemoveElementOrResetIteratorOrSetContextOrSetIteratorOrSubplansOrToBeDefinedOrUserPerformedOrVariableAssignment";
	public static final String SUBPLANS_CHILDREN = "askOrCyclicalPlanOrForEachPlanOrGoToNextOrGoToPreviousOrIfThenElseOrInsertAfterIteratorOrInsertAfterPositionOrInsertBeforeIteratorOrInsertBeforePositionOrIterativePlanOrParameterAssignmentOrPlanActivationOrPutFirstOrPutLastOrReferToOrRemoveAtIteratorOrRemoveAtPositionOrRemoveElementOrResetIteratorOrSetContextOrSetIteratorOrSubplansOrToBeDefinedOrUserPerformedOrVariableAssignment";
}
